alias: 303_EV_Charging_Completed
description: |
  # EV Charging Monitor - Session Complete
  Version: 1.6.0
  Last Updated: 2025-02-25
  ## Functions:
  1. Detects charging session completion
  2. Validates final charging states
  3. Records final session metrics
  4. Provides cost and energy summaries
  ## Dependencies:
  - sensor.eveus_ev_charger_state
  - sensor.eveus_ev_charger_soc_percent
  - sensor.eveus_ev_charger_counter_a_cost
  - sensor.eveus_ev_charger_session_time
  - input_number.ev_initial_soc
  - input_number.ev_battery_capacity
triggers:
  - entity_id: sensor.eveus_ev_charger_state
    from: Charging
    to:
      - Charge Complete
      - Standby
      - Connected
    id: charging_complete
    trigger: state
conditions:
  - condition: template
    value_template: |
      {% set entities = [
        'sensor.eveus_ev_charger_soc_percent',
        'sensor.eveus_ev_charger_counter_a_cost',
        'sensor.eveus_ev_charger_session_time',
        'input_number.ev_initial_soc'
      ] %} {% set available = true %} {% for entity in entities %}
        {% if states(entity) in ['unknown', 'unavailable', 'none'] %}
          {% set available = false %}
          {% break %}
        {% endif %}
      {% endfor %} {{ available }}
  - condition: template
    value_template: >
      {% set final = states('sensor.eveus_ev_charger_soc_percent')|float(0) %}
      {% set initial = states('input_number.ev_initial_soc')|float(0) %} {{
      final > initial }}
actions:
  - data:
      title: EV 🔋 Charging Completed
      message: >
        🕒 Session Time: {{ session_data.time }} 🔋 SoC: {{
        session_data.initial_soc }}% → {{ session_data.final_soc }}% (+{{
        session_data.soc_increase }}%) ⚡ Energy: {{ session_data.initial_kwh
        }}kWh → {{ session_data.final_kwh }}kWh (+{{ session_data.added_kwh
        }}kWh) 💸 Cost: {{ session_data.cost }}₴
    action: notify.<NOTIFICATION_SERVICE_NAME>
variables:
  session_data:
    time: >
      {{ state_attr('sensor.eveus_ev_charger_session_time',
      'formatted_time')|default('0m') }}
    initial_soc: "{{ states('input_number.ev_initial_soc')|float(0)|round(0) }}"
    final_soc: "{{ states('sensor.eveus_ev_charger_soc_percent')|float(0)|round(0) }}"
    soc_increase: >
      {{ (states('sensor.eveus_ev_charger_soc_percent')|float(0) -
      states('input_number.ev_initial_soc')|float(0))|round(0) }}
    capacity: "{{ states('input_number.ev_battery_capacity')|float(0) }}"
    initial_kwh: >
      {{ (states('input_number.ev_battery_capacity')|float(0) *
      states('input_number.ev_initial_soc')|float(0) / 100)|round(1) }}
    final_kwh: >
      {{ (states('input_number.ev_battery_capacity')|float(0) *
      states('sensor.eveus_ev_charger_soc_percent')|float(0) / 100)|round(1) }}
    added_kwh: >
      {{ ((states('input_number.ev_battery_capacity')|float(0) *
      states('sensor.eveus_ev_charger_soc_percent')|float(0) / 100) - 
          (states('input_number.ev_battery_capacity')|float(0) * states('input_number.ev_initial_soc')|float(0) / 100))|round(1) }}
    cost: "{{ states('sensor.eveus_ev_charger_counter_a_cost')|float(0)|round(0) }}"
mode: single
max_exceeded: silent
