alias: 303_EV_Charging_Completed
description: |
  # EV Charging Monitor - Session Complete
  Version: 2.1.0
  Last Updated: 2025-03-15
  ## Functions:
  1. Detects charging session completion
  2. Records final session metrics
  3. Provides cost and energy summaries
triggers:
  - entity_id: sensor.eveus_ev_charger_state
    from: Charging
    to:
      - Charge Complete
      - Standby
      - Connected
    trigger: state
conditions: []
actions:
  - data:
      title: EV 🔋 Charging Completed
      message: >
        🕒 Session Time: {{ session_data.time }}

        🔋 SoC: {{ session_data.initial_soc }}% → {{ session_data.final_soc }}%
        (+{{ session_data.soc_increase }}%)

        ⚡ Energy: {{ session_data.initial_kwh }}kWh → {{ session_data.final_kwh
        }}kWh (+{{ session_data.added_kwh }})

        💸 Cost: {{ session_data.cost }}₴
    action: notify.notify
variables:
  session_data:
    time: |
      {{ states('sensor.eveus_ev_charger_session_time') }}
    initial_soc: "{{ states('input_number.ev_initial_soc')|float(0)|round(0) }}"
    final_soc: "{{ states('sensor.eveus_ev_charger_soc_percent')|float(0)|round(0) }}"
    soc_increase: |
      {{ (states('sensor.eveus_ev_charger_soc_percent')|float(0) - 
          states('input_number.ev_initial_soc')|float(0))|round(0) }}
    capacity: "{{ states('input_number.ev_battery_capacity')|float(70) }}"
    initial_kwh: |
      {{ (states('input_number.ev_battery_capacity')|float(70) * 
          states('input_number.ev_initial_soc')|float(0) / 100)|int }}
    final_kwh: |
      {{ (states('input_number.ev_battery_capacity')|float(70) * 
          states('sensor.eveus_ev_charger_soc_percent')|float(0) / 100)|int }}
    added_kwh: |
      {{ ((states('input_number.ev_battery_capacity')|float(70) * 
           states('sensor.eveus_ev_charger_soc_percent')|float(0) / 100) - 
          (states('input_number.ev_battery_capacity')|float(70) * 
           states('input_number.ev_initial_soc')|float(0) / 100))|int }}
    cost: "{{ states('sensor.eveus_ev_charger_counter_a_cost')|float(0)|round(0) }}"
mode: single
max_exceeded: silent
