alias: 303_EV_Charging_Completed
description: |
  # EV Charging Monitor - Session Complete
  1. Primary: Detects charging session completion
  2. Safety: Validates final charging states
  3. Monitoring: Records final session metrics
  4. Analysis: Provides cost and energy summaries

  Version: 1.3.2
  Last Updated: 2025-01-16

  Dependencies:
    - sensor.eveus_ev_charger_state
    - sensor.eveus_ev_charger_soc_percent
    - sensor.eveus_ev_charger_counter_a_cost
    - sensor.eveus_ev_charger_session_time
    - input_number.ev_initial_soc
    - input_number.ev_battery_capacity
triggers:
  - entity_id: sensor.eveus_ev_charger_state
    from: Charging
    to:
      - Charge Complete
      - Standby
      - Connected
    id: charging_complete
    trigger: state
conditions:
  - condition: and
    conditions:
      - condition: template
        value_template: >
          {% set vars = namespace() %} {% set vars.is_valid = true %} {% set
          required_entities = [
            'sensor.eveus_ev_charger_soc_percent',
            'sensor.eveus_ev_charger_counter_a_cost',
            'sensor.eveus_ev_charger_session_time'
          ] %} {% for entity_id in required_entities %}
            {% if states(entity_id) in ['unknown', 'unavailable', 'none'] %}
              {% set vars.is_valid = false %}
            {% endif %}
          {% endfor %} {{ vars.is_valid }}
      - condition: template
        value_template: >
          {% set final_soc =
          states('sensor.eveus_ev_charger_soc_percent')|float(0) %} {% set
          initial_soc = states('input_number.ev_initial_soc')|float(0) %} {{
          final_soc > initial_soc }}
actions:
  - data:
      title: EV 🔋 Charging Completed
      message: >
        🕒 Session Time: {{ session_time }}

        🔋 SoC: {{ initial_soc|round(0) }}% → {{ final_soc|round(0) }}% (+{{
        soc_increase|round(0) }}%)

        ⚡ Energy: {{ initial_kwh }} → {{ final_kwh }}kWh (+{{ energy_added }})

        💸 Cost: {{ session_cost }}₴
    action: notify.<NOTIFICATION SERVICE NAME>
variables:
  session_time: >
    {{ state_attr('sensor.eveus_ev_charger_session_time',
    'formatted_time')|default('0m') }}
  session_cost: "{{ states('sensor.eveus_ev_charger_counter_a_cost')|float(0)|round(0) }}"
  battery_capacity: "{{ states('input_number.ev_battery_capacity')|float(0) }}"
  initial_soc: "{{ states('input_number.ev_initial_soc')|float(0) }}"
  final_soc: "{{ states('sensor.eveus_ev_charger_soc_percent')|float(0) }}"
  soc_increase: "{{ final_soc - initial_soc }}"
  initial_kwh: "{{ (battery_capacity * initial_soc / 100)|round(1) }}"
  final_kwh: "{{ (battery_capacity * final_soc / 100)|round(1) }}"
  energy_added: "{{ (final_kwh - initial_kwh)|round(1) }}"
mode: single
max_exceeded: silent
