reset_counter_a:
  name: Reset Counter A
  description: Reset the energy counter A to zero.
  target:
    entity:
      integration: eveus
      domain: switch

enable_charging:
  name: Enable Charging
  description: Enable the charging process.
  target:
    entity:
      integration: eveus
      domain: switch

disable_charging:
  name: Disable Charging
  description: Disable the charging process.
  target:
    entity:
      integration: eveus
      domain: switch

set_charging_current:
  name: Set Charging Current
  description: Set the charging current in amperes.
  target:
    entity:
      integration: eveus
      domain: number
  fields:
    current:
      name: Current
      description: The charging current in amperes (8-32A depending on model).
      required: true
      example: "16"
      selector:
        number:
          min: 8
          max: 32
          step: 1
          unit_of_measurement: A
